### ISSUE TITLE
benchmark value error

### ISSUE THREAD

**Issue by seasideGargantua** [WHULuoJiaTeam/Model_Zoo#15]
I need help! An error happens in the training stage about dataset after I append the benchmark callback tool! qwq
Model_Zoo\Multi_View_Reconstruction\GCNet\WHU_stereo\Ascend\8chips\code\train.py

**Comment by ADHuan** [comment]
[original code url](https://github.com/WHULuoJiaTeam/Model_Zoo/blob/main/Multi_View_Reconstruction/GCNet/WHU_stereo/Ascend/8chips/code/train.py)
