### ISSUE TITLE
Add callback to Multi_View_Reconstruction models

### ISSUE THREAD

**Issue by ADHuan** [WHULuoJiaTeam/Model_Zoo#9]
Already got the backend srv api results. Good job! 🤩👍 @seasideGargantua 

The next works:
- For the backend srv:
The input/output paras should be added to backend srv api. You need to test those apis as well.

- For the Multi_View_Reconstruction benchmark
Add the callback function to the Multi_View_Reconstruction model and try to do the benchmark test. The result template has been send to you.

> ### Callback Function: [code](https://github.com/WHULuoJiaTeam/Model_Zoo/blob/main/Scene_Classification/VGG/WHU-RS19/Ascend/1chip/code/benchmark_callback.py)
> To use this callback function, you should be care of these points:
> 1. Add the eval part to you model in the train.py. (Including the metrics, eval dataset, etc.) 
> You can get more info about this part from [进阶案例：线性拟合](https://luojianet-frontend.obs.cn-central-221.ovaijisuan.com/static/docs/luojianet-docs-r1.7/tutorials/build_zh_cn/html/advanced/linear_fitting.html#)
> 2. You should add the moxing upload part to upload the result to OBS. (Check the end part of [VGG](https://github.com/WHULuoJiaTeam/Model_Zoo/blob/main/Scene_Classification/VGG/WHU-RS19/Ascend/1chip/code/train.py) and the benchmark standard)

**Comment by ADHuan** [comment]
Good job👍 Already checked 👀

Seem like metrics are not as same as eval.py's.

Suggest to do some tests, so I reopen this issue.

**Comment by seasideGargantua** [comment]
all errors have been fixed,the code can be run smoothly in modelarts
